### PR TITLE
node-fs-writefile - Cindy Le

### PR DESCRIPTION
**Pull request by cindy-le91**
Screen Shot 2023-05-12 at 12 50 33 AM
Screen Shot 2023-05-12 at 12 50 10 AM
Screen Shot 2023-05-12 at 12 53 56 AM

### CODE REVIEW

**Review by robgmerrill — CHANGES_REQUESTED** [review]
The screenshots should be of the files written :) Please update that and DM when done so I can approve!

Also, while there are a number of ways of error handling, moving forward let's use `try catch` syntax. No need to change that in this exercise though.

**Review by robgmerrill — APPROVED** [review]
I meant to approve previously 👍

**Comment by cindy-le91** [comment]
Screen Shot 2023-05-12 at 9 31 45 AM
Screen Shot 2023-05-12 at 9 32 42 AM
Screen Shot 2023-05-12 at 9 30 53 AM

**Comment by cindy-le91** [comment]
will be sure to use try/catch moving forward!

**Pull request merged**
